cppclean -I src/core \
	-I src/core/collisions \
	-I src/core/components \
	-I src/core/cutscenes \
	-I src/core/entities \
	-I src/core/debug \
	-I src/core/input \
	-I src/lifish/debug \
	-I src/lifish/ \
	-I src/lifish/conf \
	-I src/ui/ \
	-I src/third_party/ \
	-I src/lifish/entities/ \
	-I src/lifish/components/ \
	-I src/lifish/level/ --exclude src/old/ src/ | grep -v old | grep -v 'static data'
