#include "collision_layers.hpp"

/** Defines layers `a` and `b` to collide with each other.
 *  If two layers collide, the `onCollision` callback of a collider on layer `a`
 *  will be called whenever its collider intersects that of one on layer `b`.
 *  This does NOT imply the layers are solid for each other, but merely that they 
 *  interact.
 */
#define COLLIDES(a, b) \
	collide[a][b] = true; \
	collide[b][a] = true;

/** Defines layer `a` to be "solid" for `b` and vice-versa.
 *  Implies COLLIDES(a, b).
 */
#define SOLID(a, b) \
	solid[a][b] = true; \
	solid[b][a] = true; \
	collide[a][b] = true; \
	collide[b][a] = true;

using L = Game::Layers::Layer;

Game::Matrix<bool, L::N_LAYERS, L::N_LAYERS> Game::Layers::collide,
	                                     Game::Layers::solid;

void Game::Layers::init() {
	for (auto& l : collide)
		l.fill(false);
	for (auto& l : solid)
		l.fill(false);

	COLLIDES(L::PLAYERS, L::PLAYERS)
	COLLIDES(L::PLAYERS, L::ENEMIES)
	COLLIDES(L::PLAYERS, L::ENEMIES_IGNORE_BREAKABLES)
	COLLIDES(L::PLAYERS, L::ENEMY_BULLETS)
	COLLIDES(L::PLAYERS, L::BOSSES)
	COLLIDES(L::PLAYERS, L::BOSS_BULLETS)
	COLLIDES(L::PLAYERS, L::BREAKABLES)
	COLLIDES(L::PLAYERS, L::UNBREAKABLES)
	COLLIDES(L::PLAYERS, L::TRANSP_WALLS)
	COLLIDES(L::PLAYERS, L::TELEPORTS)
	COLLIDES(L::PLAYERS, L::DEFAULT) 
	COLLIDES(L::PLAYERS, L::GRABBABLE) 
	COLLIDES(L::ENEMIES, L::ENEMIES)
	COLLIDES(L::ENEMIES, L::ENEMIES_IGNORE_BREAKABLES)
	COLLIDES(L::ENEMIES, L::ENEMY_BULLETS)
	COLLIDES(L::ENEMIES, L::BOSS_BULLETS)
	COLLIDES(L::ENEMIES, L::BOSSES)
	COLLIDES(L::ENEMIES, L::BREAKABLES)
	COLLIDES(L::ENEMIES, L::UNBREAKABLES)
	COLLIDES(L::ENEMIES, L::TRANSP_WALLS)
	COLLIDES(L::ENEMIES, L::TELEPORTS)
	COLLIDES(L::ENEMIES_IGNORE_BREAKABLES, L::ENEMY_BULLETS)
	COLLIDES(L::ENEMIES_IGNORE_BREAKABLES, L::ENEMIES_IGNORE_BREAKABLES)
	COLLIDES(L::ENEMIES_IGNORE_BREAKABLES, L::BOSS_BULLETS)
	COLLIDES(L::ENEMIES_IGNORE_BREAKABLES, L::BOSSES)
	COLLIDES(L::ENEMIES_IGNORE_BREAKABLES, L::BREAKABLES)
	COLLIDES(L::ENEMIES_IGNORE_BREAKABLES, L::UNBREAKABLES)
	COLLIDES(L::ENEMIES_IGNORE_BREAKABLES, L::TRANSP_WALLS)
	COLLIDES(L::ENEMIES_IGNORE_BREAKABLES, L::TELEPORTS)
	COLLIDES(L::BOSSES, L::ENEMY_BULLETS)
	//COLLIDES(L::BOSSES, L::BOSS_BULLETS)
	COLLIDES(L::ENEMY_BULLETS, L::BREAKABLES)
	COLLIDES(L::ENEMY_BULLETS, L::UNBREAKABLES)
	//COLLIDES(L::BOSS_BULLETS, L::WALLS)
	COLLIDES(L::EXPLOSIONS, L::PLAYERS)
	COLLIDES(L::EXPLOSIONS, L::ENEMIES)
	COLLIDES(L::EXPLOSIONS, L::ENEMIES_IGNORE_BREAKABLES)
	COLLIDES(L::EXPLOSIONS, L::BOSSES)
	COLLIDES(L::EXPLOSIONS, L::BREAKABLES)
	COLLIDES(L::EXPLOSIONS, L::UNBREAKABLES)
	COLLIDES(L::EXPLOSIONS, L::TRANSP_WALLS)
	COLLIDES(L::EXPLOSIONS, L::BOMBS)

	SOLID(L::PLAYERS, L::PLAYERS)
	SOLID(L::PLAYERS, L::BREAKABLES)
	SOLID(L::PLAYERS, L::UNBREAKABLES)
	SOLID(L::PLAYERS, L::TRANSP_WALLS)
	SOLID(L::ENEMIES, L::ENEMIES)
	SOLID(L::ENEMIES, L::ENEMIES_IGNORE_BREAKABLES)
	SOLID(L::ENEMIES, L::BOSSES)
	SOLID(L::ENEMIES, L::BREAKABLES)
	SOLID(L::ENEMIES, L::UNBREAKABLES)
	SOLID(L::ENEMIES, L::TRANSP_WALLS)
	SOLID(L::ENEMIES_IGNORE_BREAKABLES, L::ENEMIES_IGNORE_BREAKABLES)
	SOLID(L::ENEMIES_IGNORE_BREAKABLES, L::BOSSES)
	SOLID(L::ENEMIES_IGNORE_BREAKABLES, L::UNBREAKABLES)
	SOLID(L::ENEMIES_IGNORE_BREAKABLES, L::TRANSP_WALLS)
	SOLID(L::BOSSES, L::ENEMY_BULLETS)
	SOLID(L::BOSSES, L::BREAKABLES)
	SOLID(L::BOSSES, L::UNBREAKABLES)
	SOLID(L::ENEMY_BULLETS, L::BREAKABLES)
	SOLID(L::ENEMY_BULLETS, L::UNBREAKABLES)
	SOLID(L::EXPLOSIONS, L::BREAKABLES)
	SOLID(L::EXPLOSIONS, L::UNBREAKABLES)
	SOLID(L::EXPLOSIONS, L::TRANSP_WALLS)
}
