name: Make Release Builds

on: [workflow_dispatch]

jobs:
  build-macos:
    runs-on: macos-12
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: boom

      - run: ./makeapp_osx.sh

      - uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: BOOM-Remake-*-mac.dmg

  build-linux-appimage:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: boom

      - run: |
          sudo apt update
          sudo apt install -y libsfml-dev

      - run: ./makeapp_linux.sh

      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: BOOM-Remake-*-linux-x86_64.AppImage
