name: Make Release Builds

on: [workflow_dispatch]

jobs:
  build-macos-universal:
    runs-on: macos-12
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: boom

      - run: ./makeapp_osx.sh

      - uses: actions/upload-artifact@v4
        with:
          name: mac-build-universal
          path: BOOM-Remake-*-mac.dmg

  build-linux-appimage-x86_64:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: boom

      - run: |
          sudo apt update
          sudo apt install -y libsfml-dev

      - run: ./makeapp_linux.sh

      - uses: actions/upload-artifact@v4
        with:
          name: linux-build-x86_64
          path: BOOM-Remake-*-linux-x86_64.AppImage

  build-linux-appimage-aarch64:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          ref: arm

      - run: mkdir -p artifacts

      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu20.04
          githubToken: ${{ github.token }}

          dockerRunArgs: --volume "${PWD}/artifacts:/artifacts"

          install: |
            apt update
            apt install -y build-essential cmake curl libsfml-dev

          run: ./makeapp_linux.sh --prepare-github-actions

      - run: |
          cd artifacts

          archive_file="$(echo BOOM-Remake-*-linux-aarch64.tar)"
          appimage_file="${archive_file%.*}.AppImage"

          tar xf "$archive_file"

          curl -sSf -L -O https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage
          curl -sSf -L -O https://github.com/AppImage/AppImageKit/releases/download/13/runtime-aarch64
          chmod +x appimagetool-x86_64.AppImage
          chmod +x runtime-aarch64

          ./appimagetool-x86_64.AppImage --runtime-file runtime-aarch64 --no-appstream lifish.AppDir "$appimage_file"

      - uses: actions/upload-artifact@v4
        with:
          name: linux-build-aarch64
          path: artifacts/BOOM-Remake-*-linux-aarch64.AppImage
