name: Make AppImage

on: [workflow_dispatch]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: boom

      - run: |
          sudo apt update
          sudo apt install -y libsfml-dev

      - run: ./makeapp_linux.sh

      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: BOOM-Remake-*-linux-x86_64.AppImage
