name: Make Release Builds

on: [workflow_dispatch]

jobs:
  build-macos-universal:
    runs-on: macos-13
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: boom

      - run: ./makeapp_osx.sh

      - uses: actions/upload-artifact@v4
        with:
          name: mac-build-universal
          path: BOOM-Remake-*-mac.dmg

  build-linux-appimage-x86_64:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: boom

      - run: |
          sudo apt update
          sudo apt install -y desktop-file-utils libsfml-dev

      - run: ./makeapp_linux.sh

      - uses: actions/upload-artifact@v4
        with:
          name: linux-build-x86_64
          path: BOOM-Remake-*-linux-x86_64.AppImage

  build-linux-appimage-aarch64:
    runs-on: ubuntu-22.04-arm
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: boom

      - run: |
          sudo apt update
          sudo apt install -y desktop-file-utils libsfml-dev

      - run: ./makeapp_linux.sh

      - uses: actions/upload-artifact@v4
        with:
          name: linux-build-aarch64
          path: BOOM-Remake-*-linux-aarch64.AppImage
